### ISSUE TITLE
Better choice selection

### ISSUE THREAD

**Issue by ArcticSpaceFox** [thosakwe/prompts#1]
This is nothing new, it is coming from [inquirerjs](https://www.npmjs.com/package/inquirer).

The Objective is to implement a selection which updates on keyUp and keyDown events and provides the user with visual feedback.

**Comment by thosakwe** [comment]
Resolved: https://pub.dartlang.org/packages/prompts/versions/1.3.0

Also, check out the updated `example/main.dart`.
