### ISSUE TITLE
Prompt in debug mode

### ISSUE THREAD

**Issue by ulisinn** [thosakwe/prompts#4]
I apologize if this is a trivial question, I am new to dart.
The prompt example works as expected when I compile the command-line app.
Running in debug gives me:

Inappropriate ioctl for device, errno = 25

Is there a way around this?
Thank you for your help!

**Comment by thosakwe** [comment]
Sorry, a little confused here - what do you mean by "debug mode"?

**Comment by ulisinn** [comment]
![Screen Shot 2020-04-19 at 2 19 07 PM](https://user-images.githubusercontent.com/156169/79700176-c9049b80-8248-11ea-92a7-b24864c6a8aa.png)

**Comment by ulisinn** [comment]
webstorm -> debugger -> error.
works as expected if I run (from documentation):

dart2native bin/main.dart -o bin/my_app

and then start the app from terminal.

**Comment by thosakwe** [comment]
Going to close this, as it's not a package-specific error. The WebStorm terminal doesn't support everything that a regular terminal does.
